### ISSUE TITLE
Test windows under appveyor

### ISSUE THREAD

**Issue by asottile** [chrippa/backports.shutil_get_terminal_size#6]
http://appveyor.com is pretty easy to set up -- at the least I'd suggest testing py27, py35 on appveyor (since it is kinda slow).

This should be sufficient:

appveyor.yml

``` yaml
environment:
    matrix:
        - TOXENV: py27
        - TOXENV: py35

install:
    - "SET PATH=C:\\Python35;C:\\Python35\\Scripts;%PATH%"
    - pip install tox virtualenv --upgrade

# Not a C# project
build: false

test_script: tox

cache:
    - '%LOCALAPPDATA%\pip\cache'
```
